# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Oct 27 05:30:55 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 591)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SettingsGroup = QtGui.QGroupBox(self.centralwidget)
        self.SettingsGroup.setMinimumSize(QtCore.QSize(300, 0))
        self.SettingsGroup.setMaximumSize(QtCore.QSize(300, 16777215))
        self.SettingsGroup.setObjectName("SettingsGroup")
        self.verticalLayout = QtGui.QVBoxLayout(self.SettingsGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_task2 = QtGui.QRadioButton(self.SettingsGroup)
        self.radio_task2.setChecked(False)
        self.radio_task2.setObjectName("radio_task2")
        self.verticalLayout.addWidget(self.radio_task2)
        self.frame_task2 = QtGui.QFrame(self.SettingsGroup)
        self.frame_task2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_task2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_task2.setObjectName("frame_task2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_task2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.frame_task2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.frame_task2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.task2_x1 = QtGui.QSpinBox(self.frame_task2)
        self.task2_x1.setPrefix("")
        self.task2_x1.setMinimum(0)
        self.task2_x1.setMaximum(9000)
        self.task2_x1.setProperty("value", 300)
        self.task2_x1.setObjectName("task2_x1")
        self.horizontalLayout_4.addWidget(self.task2_x1)
        self.task2_y1 = QtGui.QSpinBox(self.frame_task2)
        self.task2_y1.setPrefix("")
        self.task2_y1.setMinimum(0)
        self.task2_y1.setMaximum(9000)
        self.task2_y1.setProperty("value", 200)
        self.task2_y1.setObjectName("task2_y1")
        self.horizontalLayout_4.addWidget(self.task2_y1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.frame_task2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.task2_x2 = QtGui.QSpinBox(self.frame_task2)
        self.task2_x2.setPrefix("")
        self.task2_x2.setMinimum(0)
        self.task2_x2.setMaximum(9000)
        self.task2_x2.setProperty("value", 10)
        self.task2_x2.setObjectName("task2_x2")
        self.horizontalLayout_3.addWidget(self.task2_x2)
        self.task2_y2 = QtGui.QSpinBox(self.frame_task2)
        self.task2_y2.setPrefix("")
        self.task2_y2.setMinimum(0)
        self.task2_y2.setMaximum(9000)
        self.task2_y2.setProperty("value", 23)
        self.task2_y2.setObjectName("task2_y2")
        self.horizontalLayout_3.addWidget(self.task2_y2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame_task2)
        self.radio_task3 = QtGui.QRadioButton(self.SettingsGroup)
        self.radio_task3.setChecked(True)
        self.radio_task3.setObjectName("radio_task3")
        self.verticalLayout.addWidget(self.radio_task3)
        self.frame_task3 = QtGui.QFrame(self.SettingsGroup)
        self.frame_task3.setEnabled(False)
        self.frame_task3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_task3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_task3.setObjectName("frame_task3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_task3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.frame_task3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.frame_task3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.task3_a = QtGui.QDoubleSpinBox(self.frame_task3)
        self.task3_a.setDecimals(1)
        self.task3_a.setMinimum(0.1)
        self.task3_a.setMaximum(9000.0)
        self.task3_a.setSingleStep(0.1)
        self.task3_a.setProperty("value", 50.0)
        self.task3_a.setObjectName("task3_a")
        self.horizontalLayout_5.addWidget(self.task3_a)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtGui.QLabel(self.frame_task3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.task3_b = QtGui.QDoubleSpinBox(self.frame_task3)
        self.task3_b.setDecimals(1)
        self.task3_b.setMinimum(0.1)
        self.task3_b.setMaximum(9000.0)
        self.task3_b.setSingleStep(0.1)
        self.task3_b.setProperty("value", 50.0)
        self.task3_b.setObjectName("task3_b")
        self.horizontalLayout_7.addWidget(self.task3_b)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.frame_task3)
        self.radio_task4 = QtGui.QRadioButton(self.SettingsGroup)
        self.radio_task4.setObjectName("radio_task4")
        self.verticalLayout.addWidget(self.radio_task4)
        self.frame_task4 = QtGui.QFrame(self.SettingsGroup)
        self.frame_task4.setEnabled(False)
        self.frame_task4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_task4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_task4.setObjectName("frame_task4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_task4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ghostWidget = QtGui.QWidget(self.frame_task4)
        self.ghostWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.ghostWidget.setObjectName("ghostWidget")
        self.verticalLayout_7.addWidget(self.ghostWidget)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.addRuleButton = QtGui.QPushButton(self.frame_task4)
        self.addRuleButton.setObjectName("addRuleButton")
        self.horizontalLayout_10.addWidget(self.addRuleButton)
        self.removeRuleButton = QtGui.QPushButton(self.frame_task4)
        self.removeRuleButton.setObjectName("removeRuleButton")
        self.horizontalLayout_10.addWidget(self.removeRuleButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.alalal = QtGui.QLabel(self.frame_task4)
        self.alalal.setMinimumSize(QtCore.QSize(200, 0))
        self.alalal.setMaximumSize(QtCore.QSize(200, 16777215))
        self.alalal.setObjectName("alalal")
        self.horizontalLayout_8.addWidget(self.alalal)
        self.task4_x1 = QtGui.QSpinBox(self.frame_task4)
        self.task4_x1.setMaximum(9000)
        self.task4_x1.setProperty("value", 10)
        self.task4_x1.setObjectName("task4_x1")
        self.horizontalLayout_8.addWidget(self.task4_x1)
        self.task4_y1 = QtGui.QSpinBox(self.frame_task4)
        self.task4_y1.setMaximum(9000)
        self.task4_y1.setProperty("value", 20)
        self.task4_y1.setObjectName("task4_y1")
        self.horizontalLayout_8.addWidget(self.task4_y1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ololol = QtGui.QLabel(self.frame_task4)
        self.ololol.setMinimumSize(QtCore.QSize(200, 0))
        self.ololol.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ololol.setObjectName("ololol")
        self.horizontalLayout_9.addWidget(self.ololol)
        self.task4_x2 = QtGui.QSpinBox(self.frame_task4)
        self.task4_x2.setMaximum(9000)
        self.task4_x2.setProperty("value", 150)
        self.task4_x2.setObjectName("task4_x2")
        self.horizontalLayout_9.addWidget(self.task4_x2)
        self.task4_y2 = QtGui.QSpinBox(self.frame_task4)
        self.task4_y2.setMaximum(9000)
        self.task4_y2.setProperty("value", 200)
        self.task4_y2.setObjectName("task4_y2")
        self.horizontalLayout_9.addWidget(self.task4_y2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.frame_task4)
        self.paintButton = QtGui.QPushButton(self.SettingsGroup)
        self.paintButton.setObjectName("paintButton")
        self.verticalLayout.addWidget(self.paintButton)
        self.horizontalLayout.addWidget(self.SettingsGroup)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.SettingsGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_task2.setText(QtGui.QApplication.translate("MainWindow", "Задача 2 (рисование прямой)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Параметры прямой: две точки (x1, y1) (x2, y2)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "(x1, y1) = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "(x2, y2) = ", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_task3.setText(QtGui.QApplication.translate("MainWindow", "Задача 3 (гипербола)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "-x^2/a^2 + y^2/b^2 = 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "a = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "b = ", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_task4.setText(QtGui.QApplication.translate("MainWindow", "Задача 4 (многоугольник)", None, QtGui.QApplication.UnicodeUTF8))
        self.addRuleButton.setText(QtGui.QApplication.translate("MainWindow", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.removeRuleButton.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.alalal.setText(QtGui.QApplication.translate("MainWindow", "Прямоуг. лево-верх (x1, y1) = ", None, QtGui.QApplication.UnicodeUTF8))
        self.ololol.setText(QtGui.QApplication.translate("MainWindow", "Прямоуг. право-низ (x2, y2) =", None, QtGui.QApplication.UnicodeUTF8))
        self.paintButton.setText(QtGui.QApplication.translate("MainWindow", "Paint!", None, QtGui.QApplication.UnicodeUTF8))

